name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Déclenche le workflow uniquement sur la branche main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Utilisation d'un runner Linux

    steps:
      - name: 📥 Checkout du code
        uses: actions/checkout@v2  # Récupération du code depuis GitHub

      - name: 🔧 Installation des dépendances
        run: |
          npm install

      - name: ✅ Exécution des tests
        run: |
          npm test

      - name: 🚀 Déploiement en production
        run: |
          npm run deploy
